import { viewDetailAtom } from "@/libs/atoms/calculate/view";
import { useRecoilValue } from "recoil";

export default function Enum() {
  const data = useRecoilValue(viewDetailAtom);

  const calcVal = data?.settlementTotal ?? {};

  const table = {
    // A
    현금: {
      t: "현금",
      aVal: calcVal.a1cash,
      bVal: null,
      note: calcVal.a1cashNote,
      valKey: "a1cash",
    },
    세금계산서: {
      t: "세금계산서",
      aVal: calcVal.a1tax,
      bVal: null,
      note: calcVal.a1taxNote,
      valKey: "a1tax",
    },
    신용카드: {
      t: "신용카드",
      aVal: calcVal.a1card,
      bVal: null,
      note: calcVal.a1cardNote,
      valKey: "a1card",
    },

    a1extra1: {
      t: calcVal?.a1extra1name,
      aVal: calcVal?.a1extra1,
      bVal: null,
      note: calcVal?.a1extra1note,
      valKey: "a1extra1",
    },
    a1extra2: {
      t: calcVal?.a1extra2name,
      aVal: calcVal?.a1extra2,
      bVal: null,
      note: calcVal?.a1extra2note,
      valKey: "a1extra2",
    },
    a1extra3: {
      t: calcVal?.a1extra3name,
      aVal: calcVal?.a1extra3,
      bVal: null,
      note: calcVal?.a1extra3note,
      valKey: "a1extra3",
    },
    a1extra4: {
      t: calcVal?.a1extra4name,
      aVal: calcVal?.a1extra4,
      bVal: null,
      note: calcVal?.a1extra4note,
      valKey: "a1extra4",
    },
    a1extra5: {
      t: calcVal?.a1extra5name,
      aVal: calcVal?.a1extra5,
      bVal: null,
      note: calcVal?.a1extra5note,
      valKey: "a1extra5",
    },

    // B > b1.운영제경비
    임대료: {
      t: "임대료",
      aVal: null,
      bVal: calcVal.b1rent,
      note: calcVal.b1rentNote,
      valKey: "b1rent",
    },
    관리비: {
      t: "관리비",
      aVal: null,
      bVal: calcVal.b1maint,
      note: calcVal.b1maintNote,
      valKey: "b1maint",
    },
    전기요금: {
      t: "전기요금",
      aVal: null,
      bVal: calcVal.b1electricity,
      note: calcVal.b1electricityNote,
      valKey: "b1electricity",
    },
    도시가스: {
      t: "도시가스",
      aVal: null,
      bVal: calcVal.b1gas,
      note: calcVal.b1gasNote,
      valKey: "b1gas",
    },
    인터넷: {
      t: "인터넷",
      aVal: null,
      bVal: calcVal.b1internet,
      note: calcVal.b1internetNote,
      valKey: "b1internet",
    },
    기타경비: {
      t: "기타경비",
      aVal: null,
      bVal: calcVal.b1etcExpense,
      note: calcVal.b1etcExpenseNote,
      valKey: "b1etcExpense",
    },
    b1extra1: {
      t: calcVal?.b1extra1name,
      aVal: null,
      bVal: calcVal?.b1extra1,
      note: calcVal?.b1extra1note,
      valKey: "b1extra1",
    },
    b1extra2: {
      t: calcVal?.b1extra2name,
      aVal: null,
      bVal: calcVal?.b1extra2,
      note: calcVal?.b1extra2note,
      valKey: "b1extra2",
    },
    b1extra3: {
      t: calcVal?.b1extra3name,
      aVal: null,
      bVal: calcVal?.b1extra3,
      note: calcVal?.b1extra3note,
      valKey: "b1extra3",
    },
    b1extra4: {
      t: calcVal?.b1extra4name,
      aVal: null,
      bVal: calcVal?.b1extra4,
      note: calcVal?.b1extra4note,
      valKey: "b1extra4",
    },
    b1extra5: {
      t: calcVal?.b1extra5name,
      aVal: null,
      bVal: calcVal?.b1extra5,
      note: calcVal?.b1extra5note,
      valKey: "b1extra5",
    },

    // B > b2.수수료
    수수료: {
      title: true,
      t: "2. 수수료",
      aVal: null,
      bVal: calcVal.b2charge,
      note: calcVal.b2chargeNote,
      valKey: "b2charge",
    },

    // B > b3.상품대
    원부자재과세: {
      t: "원부자재(과세)",
      aVal: null,
      bVal: calcVal.b3material,
      note: calcVal.b3materialNote,
      valKey: "b3material",
    },
    기타비품: {
      t: "기타비품",
      aVal: null,
      bVal: calcVal.b3etc,
      note: calcVal.b3etcNote,
      valKey: "b3etc",
    },
    b3extra1: {
      t: calcVal?.b3extra1name,
      aVal: null,
      bVal: calcVal?.b3extra1,
      note: calcVal?.b3extra1note,
      valKey: "b3extra1",
    },
    b3extra2: {
      t: calcVal?.b3extra2name,
      aVal: null,
      bVal: calcVal?.b3extra2,
      note: calcVal?.b3extra2note,
      valKey: "b3extra2",
    },
    b3extra3: {
      t: calcVal?.b3extra3name,
      aVal: null,
      bVal: calcVal?.b3extra3,
      note: calcVal?.b3extra3note,
      valKey: "b3extra3",
    },
    b3extra4: {
      t: calcVal?.b3extra4name,
      aVal: null,
      bVal: calcVal?.b3extra4,
      note: calcVal?.b3extra4note,
      valKey: "b3extra4",
    },
    b3extra5: {
      t: calcVal?.b3extra5name,
      aVal: null,
      bVal: calcVal?.b3extra5,
      note: calcVal?.b3extra5note,
      valKey: "b3extra5",
    },

    // B > b4.기타
    초도물품대: {
      t: "초도물품대",
      aVal: null,
      bVal: calcVal.b4initProduct,
      note: calcVal.b4initProductNote,
      valKey: "b4initProduct",
    },
    b4extra1: {
      t: calcVal?.b4extra1name,
      aVal: null,
      bVal: calcVal?.b4extra1,
      note: calcVal?.b4extra1note,
      valKey: "b4extra1",
    },
    b4extra2: {
      t: calcVal?.b4extra2name,
      aVal: null,
      bVal: calcVal?.b4extra2,
      note: calcVal?.b4extra2note,
      valKey: "b4extra2",
    },
    b4extra3: {
      t: calcVal?.b4extra3name,
      aVal: null,
      bVal: calcVal?.b4extra3,
      note: calcVal?.b4extra3note,
      valKey: "b4extra3",
    },
    b4extra4: {
      t: calcVal?.b4extra4name,
      aVal: null,
      bVal: calcVal?.b4extra4,
      note: calcVal?.b4extra4note,
      valKey: "b4extra4",
    },
    b4extra5: {
      t: calcVal?.b4extra5name,
      aVal: null,
      bVal: calcVal?.b4extra5,
      note: calcVal?.b4extra5note,
      valKey: "b4extra5",
    },

    // C > c1.기타제경비
    카드수수료: {
      t: "카드수수료",
      aVal: null,
      bVal: calcVal.c1cardFee,
      note: calcVal.c1cardFeeNote,
      valKey: "c1cardFee",
    },
    관리비2: {
      t: "관리비",
      aVal: null,
      bVal: calcVal.c1rent,
      note: calcVal.c1rentNote,
      valKey: "c1rent",
    },
    전기요금2: {
      t: "전기요금",
      aVal: null,
      bVal: calcVal.c1electricity,
      note: calcVal.c1electricityNote,
      valKey: "c1electricity",
    },
    수도요금: {
      t: "수도요금",
      aVal: null,
      bVal: calcVal.c1water,
      note: calcVal.c1waterNote,
      valKey: "c1water",
    },
    도시가스2: {
      t: "도시가스",
      aVal: null,
      bVal: calcVal.c1gas,
      note: calcVal.c1gasNote,
      valKey: "c1gas",
    },
    배상책임보험: {
      t: "배상책임보험",
      aVal: null,
      bVal: calcVal.c1insurance,
      note: calcVal.c1insuranceNote,
      valKey: "c1insurance",
    },
    기타경비2: {
      t: "기타경비",
      aVal: null,
      bVal: calcVal.c1etcExpense,
      note: calcVal.c1etcExpenseNote,
      valKey: "c1etcExpense",
    },
    c1extra1: {
      t: calcVal?.c1extra1name,
      aVal: null,
      bVal: calcVal?.c1extra1,
      note: calcVal?.c1extra1note,
      valKey: "c1extra1",
    },
    c1extra2: {
      t: calcVal?.c1extra2name,
      aVal: null,
      bVal: calcVal?.c1extra2,
      note: calcVal?.c1extra2note,
      valKey: "c1extra2",
    },
    c1extra3: {
      t: calcVal?.c1extra3name,
      aVal: null,
      bVal: calcVal?.c1extra3,
      note: calcVal?.c1extra3note,
      valKey: "c1extra3",
    },
    c1extra4: {
      t: calcVal?.c1extra4name,
      aVal: null,
      bVal: calcVal?.c1extra4,
      note: calcVal?.c1extra4note,
      valKey: "c1extra4",
    },
    c1extra5: {
      t: calcVal?.c1extra5name,
      aVal: null,
      bVal: calcVal?.c1extra5,
      note: calcVal?.c1extra5note,
      valKey: "c1extra5",
    },

    // C > c2.기타
    이자비용: {
      t: "이자비용",
      aVal: null,
      bVal: calcVal.c2interestCost,
      note: calcVal.c2interestCostNote,
      valKey: "c2interestCost",
    },
    c2extra1: {
      t: calcVal?.c2extra1name,
      aVal: null,
      bVal: calcVal?.c2extra1,
      note: calcVal?.c2extra1note,
      valKey: "c2extra1",
    },
    c2extra2: {
      t: calcVal?.c2extra2name,
      aVal: null,
      bVal: calcVal?.c2extra2,
      note: calcVal?.c2extra2note,
      valKey: "c2extra2",
    },
    c2extra3: {
      t: calcVal?.c2extra3name,
      aVal: null,
      bVal: calcVal?.c2extra3,
      note: calcVal?.c2extra3note,
      valKey: "c2extra3",
    },
    c2extra4: {
      t: calcVal?.c2extra4name,
      aVal: null,
      bVal: calcVal?.c2extra4,
      note: calcVal?.c2extra4note,
      valKey: "c2extra4",
    },
    c2extra5: {
      t: calcVal?.c2extra5name,
      aVal: null,
      bVal: calcVal?.c2extra5,
      note: calcVal?.c2extra5note,
      valKey: "c2extra5",
    },

    // D > d1.미지급금
    원부자재면세: {
      t: "원부자재(면세)",
      aVal: null,
      bVal: calcVal.d1material,
      note: calcVal.d1materialNote,
      valKey: "d1material",
    },

    매장관리비: {
      t: "매장관리비",
      aVal: null,
      bVal: !isNaN(calcVal.d1storeMaint) ? calcVal.d1storeMaint : 0,
      note: calcVal.d1storeMaintNote,
      valKey: "d1storeMaint",
    },
    전월이월금: {
      t: "전월이월금",
      aVal: null,
      bVal: calcVal.d1carryover,
      note: calcVal.d1carryoverNote,
      valKey: "d1carryover",
    },
    d1extra1: {
      t: calcVal?.d1extra1name,
      aVal: null,
      bVal: calcVal?.d1extra1,
      note: calcVal?.d1extra1note,
      valKey: "d1extra1",
    },
    d1extra2: {
      t: calcVal?.d1extra2name,
      aVal: null,
      bVal: calcVal?.d1extra2,
      note: calcVal?.d1extra2note,
      valKey: "d1extra2",
    },
    d1extra3: {
      t: calcVal?.d1extra3name,
      aVal: null,
      bVal: calcVal?.d1extra3,
      note: calcVal?.d1extra3note,
      valKey: "d1extra3",
    },
    d1extra4: {
      t: calcVal?.d1extra4name,
      aVal: null,
      bVal: calcVal?.d1extra4,
      note: calcVal?.d1extra4note,
      valKey: "d1extra4",
    },
    d1extra5: {
      t: calcVal?.d1extra5name,
      aVal: null,
      bVal: calcVal?.d1extra5,
      note: calcVal?.d1extra5note,
      valKey: "d1extra5",
    },

    // D > d2.선수금
    현금매출: {
      t: "현금매출",
      aVal: null,
      bVal: calcVal.d2cash,
      note: calcVal.d2cashNote,
      valKey: "d2cash",
    },
    d2extra1: {
      t: calcVal?.d2extra1name,
      aVal: null,
      bVal: calcVal?.d2extra1,
      note: calcVal?.d2extra1note,
      valKey: "d2extra1",
    },
    d2extra2: {
      t: calcVal?.d2extra2name,
      aVal: null,
      bVal: calcVal?.d2extra2,
      note: calcVal?.d2extra2note,
      valKey: "d2extra2",
    },
    d2extra3: {
      t: calcVal?.d2extra3name,
      aVal: null,
      bVal: calcVal?.d2extra3,
      note: calcVal?.d2extra3note,
      valKey: "d2extra3",
    },
    d2extra4: {
      t: calcVal?.d2extra4name,
      aVal: null,
      bVal: calcVal?.d2extra4,
      note: calcVal?.d2extra4note,
      valKey: "d2extra4",
    },
    d2extra5: {
      t: calcVal?.d2extra5name,
      aVal: null,
      bVal: calcVal?.d2extra5,
      note: calcVal?.d2extra5note,
      valKey: "d2extra5",
    },

    // D > d3.선급금
    임대료2: {
      t: "임대료",
      aVal: calcVal.d3rent,
      bVal: null,
      note: calcVal.d3rentNote,
      valKey: "d3rent",
    },
    초도물품대2: {
      t: "초도물품대",
      aVal: calcVal.d3initProduct ?? 0,
      bVal: null,
      note: calcVal.d3initProductNote,
      valKey: "d3initProduct",
    },
    d3extra1: {
      t: calcVal?.d3extra1name,
      aVal: calcVal?.d3extra1,
      bVal: null,
      note: calcVal?.d3extra1note,
      valKey: "d3extra1",
    },
    d3extra2: {
      t: calcVal?.d3extra2name,
      aVal: calcVal?.d3extra2,
      bVal: null,
      note: calcVal?.d3extra2note,
      valKey: "d3extra2",
    },
    d3extra3: {
      t: calcVal?.d3extra3name,
      aVal: calcVal?.d3extra3,
      bVal: null,
      note: calcVal?.d3extra3note,
      valKey: "d3extra3",
    },
    d3extra4: {
      t: calcVal?.d3extra4name,
      aVal: calcVal?.d3extra4,
      bVal: null,
      note: calcVal?.d3extra4note,
      valKey: "d3extra4",
    },
    d3extra5: {
      t: calcVal?.d3extra5name,
      aVal: calcVal?.d3extra5,
      bVal: null,
      note: calcVal?.d3extra5note,
      valKey: "d3extra5",
    },
  };

  return { table };
}
